### ISSUE TITLE
Draw new icons for priority outdoor POIs

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#17]
Replace generic sprites with custom artwork. Followup to #1.

- [x] `trailhead` ([example](http://tangrams.github.io/outdoor-style/#18/37.78762/-122.49055))
- [x] `ranger_station` ([example](http://tangrams.github.io/outdoor-style/#14/37.1691/-122.2229) and [2](http://tangrams.github.io/outdoor-style/#15/37.9040/-122.6045))
- [x] `caravan_site` - RV campground ([example](http://tangrams.github.io/outdoor-style/#15/37.4996/-122.4688))
- [x] `picnic_table` ([example](http://tangrams.github.io/outdoor-style/#19/38.54983/-121.78582))
- [x] `picnic_site` - can have same icon as `picnic_table`  ([example](http://tangrams.github.io/outdoor-style/#18/37.78170/-122.39353))
- [x] `monument` – we can reuse icon from `landmark`, no special recolouring though ([example](http://tangrams.github.io/outdoor-style/#18/38.88950/-77.04019))
- [x] `bbq` ([example](http://tangrams.github.io/outdoor-style/#17/37.91928/-122.04312))
- [x] `dog_park` ([example](http://tangrams.github.io/outdoor-style/#18/37.74208/-122.42812))
- [x] `firepit`  ([example](http://tangrams.github.io/outdoor-style/#18/39.32031/-120.98941))
- [x] `swimming_area` ([example](http://tangrams.github.io/outdoor-style/#16/38.8413/-79.3685))
- [x] `waterfall` ([example](http://tangrams.github.io/outdoor-style/#15/37.7528/-119.5927))
- [x] `fishing_area` ([example](http://tangrams.github.io/outdoor-style/#17/38.51678/-121.75711)) NOTE: was incorrectly specified here as `fishing_spot` before.
- [x] `slipway` - boat ramp ([example](http://tangrams.github.io/outdoor-style/#18/37.88935/-122.44630))
- [x] `shower` ([example](http://tangrams.github.io/outdoor-style/#18/37.83242/-122.53789))

**Comment by sensescape** [comment]
All of the above have icons, but the 3 unchecked example links don't show them: picnic_table, fishing_area and slipway

**Comment by sensescape** [comment]
Woot!
