### ISSUE TITLE
Draw new icons for outdoor that aren't priority

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#36]
Following up from https://github.com/tangrams/outdoor-style/issues/17.

### group 1: 

- [x] `water_park` ([example](http://tangrams.github.io/outdoor-style/#16/37.9740/-122.0515))
- [x] `beach_resort` ([example](http://tangrams.github.io/outdoor-style/#17/22.87750/-109.90505))
- [x] `hot_spring` ([example](http://tangrams.github.io/outdoor-style/#18/35.58797/-120.64210))
- [x] `geyser` ([example](http://tangrams.github.io/outdoor-style/#18/38.59669/-122.60220))
- [x] `toilet` see Golden Gate Park. It's grey, let's live in full color.

### group 2: 

- [x] `fishing` - a shop ([example](http://tangrams.github.io/outdoor-style/#16/38.5185/-121.7587))
- [x] `hunting` - a shop ([example](http://tangrams.github.io/outdoor-style/#19/40.80336/-124.15660))
- [x] `outdoor` - a shop ([example](http://tangrams.github.io/outdoor-style/#18/40.70072/-111.80074))
- [x] `scuba_diving` - a shop ([example](http://tangrams.github.io/outdoor-style/#18/37.86818/-122.49844))
- [x] `dive_centre` ([example](http://tangrams.github.io/outdoor-style/#19/35.24839/-120.68262))
- [x] `gas` - cooking gas canister sales ([example](http://tangrams.github.io/outdoor-style/#17/37.28465/-121.99849)), will be `gas_canister` soon.
- [x] `observatory` ([example](http://tangrams.github.io/outdoor-style/#15/39.2790/-75.5766))
- [x] `telescope` ([example](http://tangrams.github.io/outdoor-style/#19/37.34150/-121.64229))
- [x] `boat_rental` ([example](http://tangrams.github.io/outdoor-style/#18/40.19933/-88.37883))

### Don't need special treatment

- [x] `attraction` We're using a generic dot now. But a STAR might be nice. See Golden Gate Park.
- [x] `summer_camp` ([example](http://tangrams.github.io/outdoor-style/#17/45.56141/-78.70565))
- [x] `recreation_track` ([example](http://tangrams.github.io/outdoor-style/#19/37.72461/-122.47812))
- [ ] `battlefield` ([example](http://tangrams.github.io/outdoor-style/#18/39.46753/-77.73610))
- [x] `fort` ([example](http://tangrams.github.io/outdoor-style/#18/37.00325/-76.30502))
- [x] `motorcycle` ([example](http://tangrams.github.io/outdoor-style/#20/37.77381/-122.41107))
- [x] `dam` ([example](http://tangrams.github.io/outdoor-style/#13/37.9488/-119.7577)) use generic? Or maybe a new "circle" dot option for generic?
- [x] `mine` - in tiles for a couple releases  ([example](http://tangrams.github.io/outdoor-style/#15/37.9254/-121.9493)). 
- [x] But keep the `quarry` icon as pick.
- [x] watertower. See park by Nathaniel's house.

**Comment by nvkelso** [comment]
Over to me to specify list.

**Comment by nvkelso** [comment]
Split off some icons into: https://github.com/tangrams/outdoor-style/issues/48

**Comment by sensescape** [comment]
can't see battlefield after adding icon

**Comment by nvkelso** [comment]
Ha, battlefield icons look like light sabers!

Fixed battlefield icons in eb1b3ae4cb8a5e1010c791bfc06cec57fd7346c6.
